// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// SECURITY: shared secret that authenticates calls to privileged edge functions.
// Set VITE_FUNCTION_SECRET (frontend) to the SAME value as FUNCTION_SHARED_SECRET
// (server). When both are set, every functions.invoke() carries it automatically,
// closing the "anyone with the URL can invoke trading functions" hole.
// See docs/SECURITY-AND-ROADMAP.md for the caveat about secrets in a public SPA.
const FUNCTION_SECRET = import.meta.env.VITE_FUNCTION_SECRET as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// This app has NO Supabase Auth/login flow — it talks to the local stack purely
// with the publishable/anon key. Persisting a session is therefore not just
// pointless but harmful: after re-running `npm run setup` (which can rotate the
// local JWT secret), a stale session token left in localStorage gets sent as
// `Authorization: Bearer <expired-jwt>` and PostgREST rejects it with 401 —
// even though the anon key is valid. Disabling session persistence makes the
// client always authenticate with the anon key, eliminating those 401s.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  },
  global: FUNCTION_SECRET
    ? { headers: { 'x-function-secret': FUNCTION_SECRET } }
    : {},
});